### ISSUE TITLE
回忆了一下

### ISSUE THREAD

**Issue by nobodxbodon** [luoyou/stone#1]
https://gitee.com/zhishi/shitou 里的代码应该是做完了第六章. 单元测试里的BasicInterpreterTest只是用来运行文件中的stone源码, 没有什么断言(assert). BasicParserTest和LexerTest有些内容, 检查一些基本的表达式.
对第六章引进的Gluonj没有深入研究.
最后一点尝试是把BasicInterpreter.run改成有返回值的, 以便添加测试用例, 但未果.

**Comment by luoyou** [comment]
这两天把书仔细的翻了下，代码位于第17章，有详细的代码，不过因为之前没有学过java，所以还在研究代码中。

**Comment by nobodxbodon** [comment]
从原作者的[原书主页](https://chibash.github.io/essays/book)找到源码repo: https://github.com/chibash/stone 试了一下第六(chap6/Runner)和十章(chap10/ArrayRunner)的运行都没问题.

另有些读者的repo, 如: [自制编译器+自制脚本语言+自制编程语言  三书比较？ - 吴聪的回答 - 知乎](https://www.zhihu.com/question/27686032/answer/122852863).

**Comment by nobodxbodon** [comment]
刚写成了之前没搞定的解释器测试, 详见[自制编译器+自制脚本语言+自制编程语言  三书比较？ - 中文编程的回答 - 知乎](https://www.zhihu.com/question/27686032/answer/621549753)
下面打算继续在[此repo](https://github.com/program-in-chinese/stone/)继续学习+测试.
